export {
  type InboundAcceptResult,
  type InboundMailMessage,
  type InboundMailTransport,
  isMailTransportKind,
  MAIL_DIRECTIONS,
  MAIL_IMPLEMENTATION_STATUS,
  MAIL_TRANSPORT_CATALOGUE,
  MAIL_TRANSPORT_KINDS,
  type MailboxRecord,
  type MailCapabilityStatus,
  type MailDirection,
  type MailImplementationStatus,
  type MailTransportDescriptor,
  type MailTransportKind,
  mailCapabilityStatus,
  type OutboundMailMessage,
  type OutboundMailTransport,
  type OutboundSubmitResult,
} from './contracts.js';
