import { defineRbac } from '@aspec/rbac';

/** Permissions seeded for the control plane. Mail and identity areas are reserved names. */
export const PLATFORM_PERMISSIONS = [
  { key: 'platform:admin', description: 'Full administrative access to the control plane.' },
  { key: 'users:read', description: 'Read user identities and profiles.' },
  { key: 'users:update', description: 'Update user profiles and account state.' },
  { key: 'users:suspend', description: 'Suspend or reinstate users.' },
  { key: 'users:delete', description: 'Request or complete user deletion.' },
  { key: 'users:invite', description: 'Invite users into the organisation.' },
  { key: 'orgs:read', description: 'Read organisation and membership data.' },
  { key: 'orgs:update', description: 'Update the organisation.' },
  { key: 'orgs.members:read', description: 'List organisation members.' },
  { key: 'orgs.members:manage', description: 'Change organisation memberships.' },
  { key: 'orgs:invite', description: 'Invite organisation members.' },
  { key: 'orgs:settings', description: 'Change organisation settings.' },
  { key: 'groups:read', description: 'Read security and distribution groups.' },
  { key: 'groups:manage', description: 'Create and change groups and membership.' },
  { key: 'audit:read', description: 'Read administrative and security audit events.' },
  { key: 'system:read', description: 'Read system health and diagnostics.' },
  { key: 'mail:read', description: 'Read mailbox and mail-transport configuration.' },
  { key: 'mail:manage', description: 'Manage mailboxes, aliases and mail transport.' },
  { key: 'apps:read', description: 'Read registered applications.' },
  { key: 'apps:manage', description: 'Manage application registrations.' },
  { key: 'domains:read', description: 'Read custom domains.' },
  { key: 'domains:manage', description: 'Manage custom domains and DNS verification.' },
  { key: 'security:read', description: 'Read roles and sessions.' },
  { key: 'security:manage', description: 'Revoke sessions and change security settings.' },
  { key: 'migration:read', description: 'Read migration jobs. Future work.' },
  { key: 'migration:manage', description: 'Run mailbox migrations. Future work.' },
] as const;

export const PLATFORM_OWNER_ROLE = 'tenant.owner';

export const platformRbacDefinition = defineRbac({
  permissions: [...PLATFORM_PERMISSIONS],
  roles: [
    {
      key: PLATFORM_OWNER_ROLE,
      name: 'Organisation owner',
      description:
        'First administrator created during setup. Holds every control-plane permission.',
      permissions: PLATFORM_PERMISSIONS.map((permission) => permission.key),
    },
    {
      key: 'tenant.admin',
      name: 'Administrator',
      description: 'Day-to-day organisation administration.',
      parents: [],
      permissions: [
        'users:read',
        'users:update',
        'users:suspend',
        'users:invite',
        'orgs:read',
        'orgs:update',
        'orgs.members:read',
        'orgs.members:manage',
        'orgs:invite',
        'orgs:settings',
        'groups:read',
        'groups:manage',
        'audit:read',
        'system:read',
        'mail:read',
        'mail:manage',
        'apps:read',
        'apps:manage',
        'domains:read',
        'domains:manage',
        'security:read',
        'security:manage',
        'migration:read',
        'migration:manage',
      ],
    },
    {
      key: 'tenant.auditor',
      name: 'Auditor',
      description: 'Read-only access to administration and audit history.',
      permissions: [
        'users:read',
        'orgs:read',
        'orgs.members:read',
        'groups:read',
        'audit:read',
        'system:read',
        'mail:read',
        'apps:read',
        'domains:read',
        'security:read',
        'migration:read',
      ],
    },
  ],
});
